[plugins]
  [plugins.stargz]
    insecure = ["127.0.0.1", "localhost", "registry2"]
    cache_chunk_size = 50000
    lru_max_entry = 5000
    http_cache_type = "directory"
    filesystem_cache_type = "directory"
  [plugins.cvmfs]
